baseURL = "http://localhost/hpc-scorpion/"
publishDir = "private"
buildDrafts = true
title = "Scorpion — HPC cluster of biology.tohoku.ac.jp"
languageCode = "ja"
hasCJKLanguage = true
noTimes = true
disableKinds = ["RSS"]

[author]
name = "Watal M. Iwasaki"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[module]
workspace = "hugo.work"
[[module.imports]]
path = "github.com/heavywatal/hugo-theme-nonblog"

[params]
logo_src = "logo.png"
logo_alt = "logo.png"
theme_color = "#400E82"
